#!/bin/sh

has_warnings=0
dir=$PWD/`dirname $0`

echo ""

if [ ! -h ~/.vim ]; then
    ln -s $dir/.vim ~/.vim
    echo "Created link to ~/.vim"
else
    has_warnings=1
    echo $'\033[0;31mWARNING: ~/.vim already exists\033[0m'
fi

if [ ! -h ~/.vimrc ]; then
    ln -s $dir/.vimrc ~/.vimrc
    echo "Created link to ~/.vimrc"
else
    has_warnings=1
    echo $'\033[0;31mWARNING: ~/.vimrc already exists\033[0m'
fi

if  ((has_warnings==1)); then
    echo ""
    echo $'HINT:\tYou should remove or rename ~/.vim and ~/.vimrc'
    echo $'\tand run this script again.'
else
    echo ""
    echo $'\033[0;32mOK: Installation successfull.\033[0m'
fi

echo ""
