#!/bin/sh

has_warnings=0

echo ""

if [[ ! -dh ~/.vim ]]; then
    ln -s $PWD/.vim ~/.vim
else
    has_warnings=1
    echo "\033[0;31mWARNING: ~/.vim already exists\033[0m"
fi

if [[ ! -fh ~/.vimrc ]]; then
    ln -s $PWD/.vimrc ~/.vimrc
else
    has_warnings=1
    echo "\033[0;31mWARNING: ~/.vimrc already exists\033[0m"
fi

if  ((has_warnings==1)); then
    echo ""
    echo "HINT:\tYou should remove or rename ~/.vim and ~/.vimrc"
    echo "\tand run this script again."
    echo ""
fi
