#!/bin/sh

# open vimfiles directory for git submodules update to work
script_path="$PWD/`dirname $0`"
cd $script_path

echo ""
echo $'\033[0;33mTrying to update all\033[0m'
echo ""

echo "vimfiles:"
git pull origin master

git submodule -q foreach 'echo "";echo "$name:"; git pull origin master'

echo ""
echo $'\033[0;32mUpdate complete.\033[0m'
