#!/bin/sh
echo "\033[0;44m                  \033[0m"
echo "\033[0;44m    UPDATE ALL    \033[0m"
echo "\033[0;44m                  \033[0m"

echo "\033[0;32mvimfiles\033[0m"
git pull

git submodule -q foreach 'echo "\033[0;32m$name\033[0m"; git pull origin master'
